replicaCount: 1

image:
  repository: jampiersantiagomorenoarenas/k8s-demo
  pullPolicy: Always
  tag: "10a2c1f32c830f90e07b826dabff22f14871f269"

service:
  type: NodePort
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
