replicaCount: 1

image:
  repository: jampiersantiagomorenoarenas/k8s-demo
  pullPolicy: Always
  tag: "ef0e10105e066aa0fac38ed60da32dd06b1b2ab9"

service:
  type: NodePort
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
